malone12/SVCPLAN-5322/improve_lnet_rpc_stats
ncsa/control-repo pull request #182
Opened 2024-04-17 18:31 UTC by jdmaloney

@jakerundall Updating this repo with new Lustre module version (v3.1.0, up from 2.0.2 that was in here before)

2024-04-17 18:39 UTC, billglick commented
I'm kind of torn on this request.

We know there are further fixes that need to be made to the ncsa/profile_lustre module to address stateful nodes ([SVCPLAN-5268](https://jira.ncsa.illinois.edu/browse/SVCPLAN-5268)). I think I'd prefer to hold off until that fix is in place before updating to any of the v3 ncsa/profile_lustre versions in `control-repo`.

2024-04-24 16:24 UTC, jakerundall commented
We can update this PR, or start a new one, to reference [v3.2.0|https://github.com/ncsa/puppet-profile_lustre/releases/tag/v3.2.0] instead.

2024-05-21 11:43 UTC, billglick commented
Can this be updated to point to tag v3.2.0?

2024-05-21 20:32 UTC, jdmaloney commented
@billglick Yeah; will do here momentarily

2024-05-21 20:59 UTC, jdmaloney commented
@billglick I've rebased and updated this to v3.2.0

2024-05-21 21:49 UTC, billglick requested changes
Still pointing v3.1..0

2024-05-21 21:49 UTC, billglick commented on Puppetfile
> +mod 'ncsa/profile_lustre', tag: 'v3.1.0',  git: 'https://github.com/ncsa/puppet-profile_lustre'
it is still showing v3.1.0.

```suggestion
mod 'ncsa/profile_lustre', tag: 'v3.2.0',  git: 'https://github.com/ncsa/puppet-profile_lustre'
```

2024-05-21 21:52 UTC, billglick approved these changes

2024-05-21 21:53 UTC, jdmaloney commented
@billglick Fixed; thought I had it in there when I rebased.

2024-05-21 23:01 UTC, merged