Topic/mtlong2/asdplng 50 review profile rsyslog 2
ncsa/control-repo pull request #9
Opened 2021-06-22 20:14 UTC by mattlongt

PR to add updated profile_rsyslog to control repo and base role.

2021-06-22 20:43 UTC, billglick commented
@mattlongt Can you rebase these commits?

2021-06-22 21:01 UTC, mattlongt commented
@billglick thanks for the note. Just realized I've been rebasing wrong this whole time. Should look better now.

2021-06-22 21:02 UTC, billglick requested changes
Not referencing the tag for profile_rsyslog

2021-06-22 21:02 UTC, billglick commented on Puppetfile
> +mod 'ncsa/profile_rsyslog', commit: 'a877ec02fe1b17d6c6e1d68d25eaf1ed9e7a1886', git: 'https://github.com/ncsa/puppet-profile_rsyslog'
This seems to have reverted. It should be referencing your recently tagged version instead of a commit.

2021-06-22 21:21 UTC, billglick commented
I'm also confused why there appears to not be anything configured in control repo to forward logs to Security. Perhaps I'm overlooking that?

2021-06-23 14:05 UTC, mattlongt commented on Puppetfile
> +mod 'ncsa/profile_rsyslog', commit: 'a877ec02fe1b17d6c6e1d68d25eaf1ed9e7a1886', git: 'https://github.com/ncsa/puppet-profile_rsyslog'
Weird, I'm probably still learning how to rebase the right way and wiped something out. That's been fixed back now.

2021-06-23 14:06 UTC, billglick requested changes
I don't think `base.pp` is including the correct class.

2021-06-23 14:06 UTC, billglick commented on site-modules/profile/manifests/base.pp
> +  include ::profile::rsyslog::client
Shouldn't this be including `::profile_rsyslog`?

```suggestion
  include ::profile_rsyslog
```

2021-06-23 14:07 UTC, mattlongt commented on site-modules/profile/manifests/base.pp
> +  include ::profile::rsyslog::client
This got wiped out in my rebase again as well.

2021-06-23 14:22 UTC, mattlongt commented
@billglick you're not overlooking anything. I just didn't want to make assumptions on where logs are supposed to be directed by default. The relay functionality to security is less useful anyway unless the clients are also configured. For now this is done per site/cluster/node. I've written up some documentation in the wiki on how hiera should be setup to send logs to the right places.

It would be trivial to add forwarding to security to the profile itself, but it might be helpful to wait on that until we can also safely set a variable default on the client portion to send logs to a central node in a site (like an xcat server), which then gets passed on to security.

2021-06-23 15:02 UTC, billglick commented
> @billglick you're not overlooking anything. I just didn't want to make assumptions on where logs are supposed to be directed by default. The relay functionality to security is less useful anyway unless the clients are also configured. For now this is done per site/cluster/node. I've written up some documentation in the wiki on how hiera should be setup to send logs to the right places.

Can you at least add an example in the `README.md` of how to forward logs an example log server? I think that would be a common use for this profile, and it is not obvious to me at this point of how to enable that via this profile.

2021-07-09 21:33 UTC, billglick commented on data/common.yaml
> +            timeout: "6"
I think we should forward logs to the NCSA Security loghost by default. My thinking is that anything that gets setup should forward to security by default. If a project is setting up their own control repo from the template, they can then choose to change the forwarding to their own relay host if they want, but by default we start off forwarding them centrally. The counter argument is that it advertises NCSA’s primary loghost hostname and listening port.

2021-07-12 16:26 UTC, billglick commented
The latest changes include:
- Update to `ncsa/profile_rsyslog` v0.1.1 (updated README with example)
- Inclusion of default data to `config_rulesets` to forward to NCSA's default security loghost
- Update to `puppet/rsyslog` to version 5.2.0

2021-07-12 16:35 UTC, andylytical commented on data/common.yaml
> +            timeout: "6"
Can we take this opportunity to move this "default" data to the profile?

2021-07-12 17:40 UTC, billglick commented
The latest changes include:
- Add new rsyslog profile to Puppetfile and added client profile to base.pp
- Update puppet/rsyslog to version 5.2.0
- Move default profile_rsyslog data to ncsa/profile_rsyslog module
- Update ncsa/profile_rsyslog to tag v0.1.2

2021-07-12 17:46 UTC, andylytical approved these changes

2021-07-12 17:49 UTC, merged